Homework3
NickGorev/made_2019_cpp pull request #1
Opened 2019-11-04 13:39 UTC by NickGorev

Домашнее задание номер 3.
Николай Горев
Группа MADE-12

2019-11-05 09:25 UTC, smirnov-vs requested changes

2019-11-05 09:25 UTC, smirnov-vs commented on 03/parser.h
> +                Callback numberCallback = nullptr)
так как это функторы, лучше передавать по-ссылке

2019-11-05 09:25 UTC, smirnov-vs commented on 03/parser.h
> +        void parse(std::string);
данные копируются

2019-11-05 09:25 UTC, smirnov-vs commented on 03/parser.h
> +        using Callback = std::function<void (std::string)>;
и тут

2019-11-05 09:25 UTC, smirnov-vs commented on 03/parser.h
> +        using mutatingCallback = std::function<void (std::string&)>;
изменять исходный объект не нужно

2019-11-05 09:25 UTC, smirnov-vs commented on 03/parser.cpp
> +                numberCallback(token);
колбэк для чисел, а отдает строки

2019-11-05 13:11 UTC, NickGorev commented on 03/parser.h
> +                Callback numberCallback = nullptr)
Это и следующие замечания пофиксил в следующих трех коммитах. В данном случае заменил тип на константную ссылку.

2019-11-05 13:12 UTC, NickGorev commented on 03/parser.h
> +        void parse(std::string);
заменил аргумент функции на константную ссылку

2019-11-05 13:12 UTC, NickGorev commented on 03/parser.h
> +        using Callback = std::function<void (std::string)>;
и тут заменил

2019-11-05 13:15 UTC, NickGorev commented on 03/parser.h
> +        using mutatingCallback = std::function<void (std::string&)>;
Добавил const, хотя, по моему мнению, это уменьшает гибкость парсера. В этом колбэке можно было бы производить предварительную обработку строки. Например, удаление знаков препинания, или замену заглавных букв строчными...

2019-11-05 13:21 UTC, NickGorev commented on 03/parser.cpp
> +                numberCallback(token);
Переделал. Теперь в колбэк в виде аргумента передается число, преобразованное в int. Считаю, что в данном случае передавать аргумент по ссылке не имеет смысла из-за размера int. Наш парсер снова теряет гибкость: целые числа могут быть разного размера: int, short, long. Этим можно было управлять при преобразовании строки в число в колбэке. А теперь придется пересобирать библиотеку для  нового типа целых.

2019-11-06 12:50 UTC, smirnov-vs commented on 03/parser.h
> +        using mutatingCallback = std::function<void (std::string&)>;
да, но парсер ничего не делает с результатом дальше, так что пока это логично

2019-11-06 12:50 UTC, smirnov-vs commented on 03/parser.cpp
> +                numberCallback(token);
можно взять самое большое uint64_t и не париться, довольно большое число

2019-11-06 12:51 UTC, smirnov-vs approved these changes

2019-11-06 13:01 UTC, merged