homework 7
NickGorev/made_2019_cpp pull request #5
Opened 2019-12-04 07:21 UTC by NickGorev

2019-12-04 09:59 UTC, smirnov-vs requested changes

2019-12-04 09:59 UTC, smirnov-vs commented on 07/FormatString.h
> +        arg_number = std::stoi(number_string);
а зачем все проверки сверху, если stoi делает примерно те же вещи?

2019-12-04 09:59 UTC, smirnov-vs commented on 07/FormatString.h
> +        std::string::size_type close_bracket_pos = format_string.find("}", search_pos);
лучше идти посимвольно и анализировать есть ли там `{ }`

2019-12-04 13:07 UTC, NickGorev commented on 07/FormatString.h
> +        arg_number = std::stoi(number_string);
Удалил часть проверок, но не все, так как stoi не проверяет "остаток" строки. Например, с точки зрения stoi строка "123abc" корректно преобразуется в число 123.

2019-12-04 13:08 UTC, NickGorev commented on 07/FormatString.h
> +        std::string::size_type close_bracket_pos = format_string.find("}", search_pos);
Переделал.

2019-12-05 19:55 UTC, smirnov-vs approved these changes
привет!
все хорошо

2019-12-08 04:14 UTC, merged