homework 8
NickGorev/made_2019_cpp pull request #6
Opened 2019-12-08 13:39 UTC by NickGorev

2019-12-09 09:26 UTC, smirnov-vs requested changes

2019-12-09 09:26 UTC, smirnov-vs commented on 08/vector.hpp
> +              new (data_ + i) value_type;
это по сути метод `construct` аллокатора

2019-12-09 09:26 UTC, smirnov-vs commented on 08/vector.hpp
> +              data_[i].~value_type();
`destroy`

2019-12-09 09:26 UTC, smirnov-vs commented on 08/vector.hpp
> +                data_[i++] = *current++;
слева мусор, оператор применять нельзя, надо везде поправить

2019-12-09 12:51 UTC, NickGorev commented on 08/vector.hpp
> +              new (data_ + i) value_type;
fixed

2019-12-09 12:52 UTC, NickGorev commented on 08/vector.hpp
> +              data_[i].~value_type();
fixed

2019-12-09 12:53 UTC, NickGorev commented on 08/vector.hpp
> +                data_[i++] = *current++;
Если я правильно понял замечание, то здесь также нужно вызывать allocator::construct?

2019-12-09 12:57 UTC, NickGorev commented on 08/vector.hpp
> +                data_[i++] = *current++;
Добавил в аллокатор  методы construct и destroy. А затем в vector добавил их вызовы везде, где добавляются/уничтожаются данные.

2019-12-11 19:52 UTC, smirnov-vs approved these changes
привет!
теперь все верно

2019-12-11 19:52 UTC, smirnov-vs commented on 08/allocator.hpp
> +            ::new ((void*)p) value_type(std::forward<Args>(args)...);
кастить необязательно

2019-12-14 09:46 UTC, merged