homework 9
NickGorev/made_2019_cpp pull request #7
Opened 2019-12-15 06:25 UTC by NickGorev

2019-12-16 15:59 UTC, smirnov-vs requested changes

2019-12-16 15:59 UTC, smirnov-vs commented on 09/threadpool.hpp
> +                threads.push_back(std::async(std::launch::async,
функционал async тут избыточен

2019-12-16 15:59 UTC, smirnov-vs commented on 09/threadpool.hpp
> +                for (size_t i = 0; i < threads.size(); i++) {
это костыль, надо будет переделать на ожидание потока

2019-12-16 15:59 UTC, smirnov-vs commented on 09/threadpool.hpp
> +                if (!task.valid())
надо использовать флаг остановки

2019-12-16 15:59 UTC, smirnov-vs commented on 09/threadpool.hpp
> +            threads.clear();
лишний вызов

2019-12-17 02:50 UTC, NickGorev commented on 09/threadpool.hpp
> +                threads.push_back(std::async(std::launch::async,
переделал на std::thread

2019-12-17 02:51 UTC, NickGorev commented on 09/threadpool.hpp
> +                for (size_t i = 0; i < threads.size(); i++) {
переделал на остановку потоков по флагу

2019-12-17 02:51 UTC, NickGorev commented on 09/threadpool.hpp
> +                if (!task.valid())
fixed

2019-12-17 02:52 UTC, NickGorev commented on 09/threadpool.hpp
> +            threads.clear();
убрал threads.clear()

2019-12-23 10:02 UTC, smirnov-vs approved these changes
привет!
я зачел

2019-12-23 10:02 UTC, smirnov-vs commented on 09/threadpool.hpp
> +                threads.emplace_back(std::thread([this]{thread_task();}));
тут кстати конструктор лишний раз вызван

2019-12-23 10:02 UTC, smirnov-vs commented on 09/threadpool.hpp
> +                stop_flag = true;
переменная может быть атомарной

2019-12-23 12:38 UTC, NickGorev commented on 09/threadpool.hpp
> +                threads.emplace_back(std::thread([this]{thread_task();}));
fixed

2019-12-23 12:40 UTC, NickGorev commented on 09/threadpool.hpp
> +                stop_flag = true;
Не стал менять, т.к. не уверен, что использование атомарной переменной в данном случае существенно упростит код.

2019-12-23 12:40 UTC, merged